### ISSUE TITLE
Another Gameboard issue

### ISSUE THREAD

**Issue by jakeblack14** [jakeblack14/UnityGameBoard#5]
So sometimes when you click a piece it recognizes it as another one of your pieces. So if I click my piece that is on the second row it thinks it is the piece on the 5th row and will move based on the possible moves of the piece on the second row.

**Comment by ConnorBPhillips** [comment]
![anotherissue](https://user-images.githubusercontent.com/21352560/35836553-71da2e72-0aa6-11e8-92ed-ad581f1c45ab.PNG)
Heres a picture of the problem, the one circled is the one I clicked but you can see the other one is highlighted. 
![anotherissue1](https://user-images.githubusercontent.com/21352560/35836592-b8486f54-0aa6-11e8-8a26-8362cae2aa97.PNG)
Blue is where the piece used to be and Red is where the piece was able to go
Hopefully this helps visualizing the problem.

**Comment by ConnorBPhillips** [comment]
Apparently the piece that is circled in blue also will not move or even register that its being clicked after you move the piece its kinda connected to

**Comment by ConnorBPhillips** [comment]
That piece that wont move even though it is shown on the gameboard you can now move other pieces into that space. It shows up on the gameboard but it acts as if there is no piece there. You can move other pieces through it but the piece will always be there.

**Comment by ConnorBPhillips** [comment]
So i also figured out that this only happens to pieces that are in the same diagonal row
